# Generated by Django 4.1.5 on 2023-04-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publishes',
            new_name='Publishing',
        ),
    ]
