# Generated by Django 4.1.5 on 2023-04-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_book_sinopsys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sinopsys',
            new_name='synopsis',
        ),
    ]
